sudo: false
fast_finish: true

git:
  depth: 5

cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

env:
  global:
  - TASTY_QUICKCHECK_TESTS=10000

# TODO see if the mac haskell build is fixed soon
matrix:
  include:
  - env: GHCVER=8.6.5 STACK_YAML=stack.yaml
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.6.5
  - env: GHCVER=8.8.4 STACK_YAML=stack.yaml
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.8.4
  - env: GHCVER=8.10.2 STACK_YAML=stack.yaml
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.10.2

  # - ghc: 8.6.5
  # os: osx
  # - ghc: 8.8.4
  # os: osx
  # - ghc: 8.10.2
  # os: osx

before_install:
  # ghc
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install git-annex; else sudo apt-get install -y git-annex; fi
  - travis_wait stack --no-terminal --skip-ghc-check setup
    # - curl -sSL https://get.haskellstack.org/ | sh
    # - stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

script:
  - stack --no-terminal --skip-ghc-check test

notifications:
  email: false
