sudo: true
language: haskell
fast_finish: true

git:
  depth: 1

# TODO remove?
cabal: "3.2"

cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

env:
  global:
  - STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

os:
  - linux
  - osx

matrix:
  include:
  - ghc: 8.6.5
  - ghc: 8.8.4
  - ghc: 8.10.2

install:
  - sudo apt-get install -y git-annex
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

script:
  - stack test --system-ghc

notifications:
  email: false
