resolver: lts-14.27
packages:
- '.'
extra-deps:
- bytestring-trie-0.2.5.0
- store-0.7.7
- th-utilities-0.2.4.0
- store-core-0.4.4.3
  # - github: jefdaj/docopt.hs
  # commit: 080c3ba6badd736f1b4a3f1f13dbd4c107614136

nix:
  enable: true # TODO harmonize with niv
  pure: false
